name = "dispatch-gsheet-js"
main = "./worker.js"
compatibility_date = "2025-05-26"

# Store your GitHub PAT as a secret in the Cloudflare dashboard
[vars]
GITHUB_TOKEN = ""

# Jakarta times 10:00, 17:00, 20:00, 21:00, 22:00 WIB
# → UTC 03:00, 10:00, 13:00, 14:00, 15:00
[[triggers.crons]]
schedule = "0 3 * * *"
[[triggers.crons]]
schedule = "0 10 * * *"
[[triggers.crons]]
schedule = "0 13 * * *"
[[triggers.crons]]
schedule = "0 14 * * *"
[[triggers.crons]]
schedule = "0 15 * * *"