name: Update GSheet JS

on:
  push:
  workflow_dispatch:
  schedule:
    # Runs at 0 minutes past hours 1–4 and 8–11 UTC (Jakarta is UTC+7, so those map to 8–11 AM and 3–7 PM local)
    - cron: '0 1-4,8-11 * * *'

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install npm dependencies
        run: npm ci

      - name: Install Chromium & sandbox deps
        run: |
            sudo apt-get update
            sudo apt-get install -y chromium-browser fonts-liberation libasound2 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdbus-1-3 libgtk-3-0 libx11-xcb1 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libpango1.0-0 libnss3 lsb-release


      - name: Generate secrets.json
        run: |
          cat <<EOF > secrets.json
          {
            "APP_ID":           "${{ secrets.APP_ID }}",
            "APP_SECRET":       "${{ secrets.APP_SECRET }}",
            "SPREADSHEET_TOKEN":"${{ secrets.SPREADSHEET_TOKEN }}"
          }
          EOF

      # ← Insert your debug step here
      - name: Debug secrets
        run: |
          echo "APP_ID is $APP_ID"
          echo "SPREADSHEET_TOKEN is $SPREADSHEET_TOKEN"
        env:
          APP_ID:            ${{ secrets.APP_ID }}
          SPREADSHEET_TOKEN: ${{ secrets.SPREADSHEET_TOKEN }}

      - name: Set Timezone to GMT+7 and run scripts
        env:
          TZ:                 Asia/Jakarta
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SHEET_ID:           ${{ secrets.SHEET_ID }}
        run: |
          date
          node new_index.js


