name: Update GSheet JS

on:
  push:
  workflow_dispatch:
  schedule:
    # Runs at 0 minutes past hours 1–4 and 8–11 UTC (Jakarta is UTC+7, so those map to 8–11 AM and 3–7 PM local)
    - cron: '0 1-4,8-11 * * *'

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        # use ci for clean install based on package-lock.json
        run: npm ci
        # lockfileVersion: 3 :contentReference[oaicite:0]{index=0}
        # main entry is index.js :contentReference[oaicite:1]{index=1}

      - name: Set Timezone to GMT+7 and run scripts
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          SPREADSHEET_TOKEN: ${{ secrets.SPREADSHEET_TOKEN }}

        run: |
          export TZ=Asia/Jakarta
          date
          node new_index.js